### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bjankord**

### CODE REVIEW

**Comment by bjankord** [comment]
@mjhenkes It auto-added you as a review to this based on the CODEOWNERS file.

**Comment by mjhenkes** [comment]
@bjankord nice

**Comment by bjankord** [comment]
screen shot 2018-02-27 at 3 33 58 pm

Looks like as a code owner, you still get a notice that it is waiting on review from other code owners, which is good. Though you can also merge down as and admin which I think is good to for trivial / small changes.

**Comment by bjankord** [comment]
screen shot 2018-02-27 at 3 38 37 pm

**Pull request merged**
